apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "teleport.fullname" . }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
data:
  teleport.yaml: |-
    teleport:
      log:
        output: stderr
        severity: DEBUG
      data_dir: /var/lib/teleport
      storage:
        type: {{ .Values.config.storage_type }}

    auth_service:
      enabled: {{ .Values.config.auth_service.enabled }}
      authentication:
        type: {{ .Values.config.auth_type }}
        second_factor: {{ .Values.config.auth_second_factor}}
      public_addr: {{ .Values.config.public_addr }}:3025
      cluster_name: {{ .Values.config.cluster_name }}
      {{- if .Values.config.static_join }}
      tokens:
        - trusted_cluster:{{ .Values.config.static_join.token }}
      {{- end }}

    ssh_service:
      enabled: {{ .Values.config.ssh_service.enabled }}
      public_addr: {{ .Values.config.public_addr }}:3022
      commands:
      - name: hostname
        command: [/bin/hostname]
        period: 5m0s
      - name: uptime
        command: [/usr/bin/uptime, -p]
        period: 5m0s

    proxy_service:
      enabled: {{ .Values.config.ssh_service.enabled }}
      public_addr: {{ .Values.config.public_addr }}:3080
      ssh_public_addr: {{ .Values.config.public_addr }}:3023
      web_listen_addr: 0.0.0.0:3080
      listen_addr: 0.0.0.0:3023
      {{- if .Values.proxy.tls.enabled }}
      https_key_file: {{ .Values.config.https_key_file }}
      https_cert_file: {{ .Values.config.https_cert_file }}
      {{- end }}
      # kubernetes section configures
      # kubernetes proxy protocol support
      kubernetes:
        enabled: {{ .Values.config.kubernetes.enabled }}
        listen_addr: 0.0.0.0:3026
        # public_addr is used to set values
        # setup in kubeconfig after tsh login
        # public_addr: [kubeproxy.example.com:443]
{{- if .Values.config.trusted_cluster.enabled }}
  trusted-cluster.yaml: |-
    kind: trusted_cluster
    version: v2
    metadata:
      # the name of a trusted cluster 
      name: {{ .Values.config.trusted_cluster.name }}
    spec:
      # this field allows to create tunnels that are disabled, but can be enabled later.
      # this is the only field that can be changed later.
      enabled: true
      # the token expected by the "main" cluster:
      token: {{ .Values.config.trusted_cluster.token }}
      # the address in 'host:port' form of the reverse tunnel listening port on the
      # "master" proxy server:
      tunnel_addr: {{ .Values.config.trusted_cluster.address }}:3024
      # the address in 'host:port' form of the web listening port on the
      # "master" proxy server:
      web_proxy_addr: {{ .Values.config.trusted_cluster.address }}:3080
      role_map:
        - remote: "admin"  
          local: [editor]
{{- end }}
{{- if .Values.config.github.enabled }}
  github.yaml: |-
    kind: github
    version: v3
    metadata:
      name: github
    spec:
      display: Github
      client_id: {{ .Values.config.github.client_id }}       
      client_secret: {{ .Values.config.github.client_secret }}
      redirect_url: "https://{{ .Values.config.public_addr }}:3080/v1/webapi/github/callback"
      teams_to_logins:
        - organization: {{ .Values.config.github.organization }}
          team: {{ .Values.config.github.team }}
          logins:
            - ec2-user
            - root
          kubernetes_groups: ["system:masters"]
{{- end }}
